/*
 * Built-in sample question bank for the JEE Main mock test app.
 *
 * These are ORIGINAL practice questions written in the JEE Main style and
 * tagged with a year so the year filter can be demonstrated. They are not
 * official NTA questions. To test with real previous-year papers, import a
 * JSON or CSV file from the setup page (see README.md for the schema).
 *
 * Schema (one object per question):
 *   id        unique string
 *   subject   "Physics" | "Chemistry" | "Mathematics"
 *   chapter   chapter name (used for filters and chapter-wise analysis)
 *   year      PYQ year tag, e.g. 2025
 *   type      "MCQ" (single correct, 4 options) | "NUM" (numerical value)
 *   question  text; ^{..} renders superscript, _{..} subscript, \n a new line
 *   options   array of 4 strings (MCQ only)
 *   answer    MCQ: 0-based index of the correct option; NUM: the number
 *   solution  short worked solution (shown in the review and PDF report)
 */
window.JEE_SAMPLE_BANK = [
  // ---------------- PHYSICS ----------------
  { id: "P01", subject: "Physics", chapter: "Units and Measurements", year: 2025, type: "MCQ",
    question: "The dimensional formula of Planck's constant h is:",
    options: ["[ML²T⁻¹]", "[ML²T⁻²]", "[MLT⁻¹]", "[ML⁻¹T⁻²]"], answer: 0,
    solution: "E = hν, so h = E/ν = [ML²T⁻²]/[T⁻¹] = [ML²T⁻¹]." },
  { id: "P02", subject: "Physics", chapter: "Units and Measurements", year: 2024, type: "MCQ",
    question: "A physical quantity P = a³b²/(√c · d). The percentage errors in a, b, c and d are 1%, 3%, 4% and 2% respectively. The percentage error in P is:",
    options: ["13%", "12%", "14%", "10%"], answer: 0,
    solution: "ΔP/P = 3(1) + 2(3) + ½(4) + 1(2) = 3 + 6 + 2 + 2 = 13%." },
  { id: "P03", subject: "Physics", chapter: "Kinematics", year: 2023, type: "MCQ",
    question: "A ball is projected with a speed of 20 m/s at 30° above the horizontal (g = 10 m/s²). The maximum height reached by the ball is:",
    options: ["10 m", "5 m", "15 m", "20 m"], answer: 1,
    solution: "H = u²sin²θ / 2g = (400 × 0.25)/20 = 5 m." },
  { id: "P04", subject: "Physics", chapter: "Kinematics", year: 2026, type: "NUM",
    question: "A particle starts from rest and moves with a constant acceleration of 4 m/s². The distance travelled (in m) during the 5th second is ____.",
    answer: 18,
    solution: "sₙ = u + a(2n − 1)/2 = 0 + 4 × 9/2 = 18 m." },
  { id: "P05", subject: "Physics", chapter: "Laws of Motion", year: 2025, type: "MCQ",
    question: "Two blocks of masses 2 kg and 3 kg are in contact on a smooth horizontal surface. A horizontal force of 10 N is applied on the 2 kg block. The contact force between the blocks is:",
    options: ["4 N", "10 N", "6 N", "5 N"], answer: 2,
    solution: "a = 10/5 = 2 m/s². Contact force on the 3 kg block = 3 × 2 = 6 N." },
  { id: "P06", subject: "Physics", chapter: "Laws of Motion", year: 2024, type: "MCQ",
    question: "A 5 kg block rests on a rough horizontal surface (μₛ = 0.4, μₖ = 0.3). A horizontal force of 15 N is applied to it. The friction force acting on the block is (g = 10 m/s²):",
    options: ["20 N", "15 N", "12 N", "0 N"], answer: 1,
    solution: "Limiting friction = 0.4 × 50 = 20 N > 15 N, so the block stays at rest and static friction equals the applied force, 15 N." },
  { id: "P07", subject: "Physics", chapter: "Work, Energy and Power", year: 2023, type: "MCQ",
    question: "A body of mass 2 kg moving at 10 m/s is brought to rest by a constant retarding force over a distance of 5 m. The magnitude of the force is:",
    options: ["10 N", "40 N", "20 N", "100 N"], answer: 2,
    solution: "Work–energy theorem: F × 5 = ½ × 2 × 10² = 100 J, so F = 20 N." },
  { id: "P08", subject: "Physics", chapter: "Work, Energy and Power", year: 2026, type: "NUM",
    question: "A pump lifts 600 kg of water through a height of 10 m in 1 minute. Assuming 100% efficiency (g = 10 m/s²), the power of the pump (in W) is ____.",
    answer: 1000,
    solution: "P = mgh/t = 600 × 10 × 10 / 60 = 1000 W." },
  { id: "P09", subject: "Physics", chapter: "Rotational Motion", year: 2025, type: "MCQ",
    question: "The moment of inertia of a uniform thin rod of mass M and length L about an axis through one end and perpendicular to its length is:",
    options: ["ML²/12", "ML²/3", "ML²/2", "ML²"], answer: 1,
    solution: "I_end = I_cm + M(L/2)² = ML²/12 + ML²/4 = ML²/3." },
  { id: "P10", subject: "Physics", chapter: "Rotational Motion", year: 2024, type: "MCQ",
    question: "A solid sphere rolls without slipping on a horizontal surface. The ratio of its rotational kinetic energy to its total kinetic energy is:",
    options: ["5/7", "2/5", "1/2", "2/7"], answer: 3,
    solution: "K_rot = ½(2/5 mR²)(v/R)² = mv²/5; K_total = ½mv² + mv²/5 = 7mv²/10. Ratio = 2/7." },
  { id: "P11", subject: "Physics", chapter: "Gravitation", year: 2023, type: "MCQ",
    question: "The escape velocity from the Earth's surface is 11.2 km/s. For a planet with twice the Earth's radius and the same mean density, the escape velocity is:",
    options: ["11.2 km/s", "22.4 km/s", "15.8 km/s", "5.6 km/s"], answer: 1,
    solution: "vₑ = √(2GM/R) = R√(8πGρ/3), so vₑ ∝ R at constant density: 2 × 11.2 = 22.4 km/s." },
  { id: "P12", subject: "Physics", chapter: "Gravitation", year: 2025, type: "MCQ",
    question: "At what height above the Earth's surface does the acceleration due to gravity become one-fourth of its value at the surface? (R = radius of the Earth)",
    options: ["2R", "R/2", "3R", "R"], answer: 3,
    solution: "g' = g R²/(R + h)² = g/4 ⇒ R + h = 2R ⇒ h = R." },
  { id: "P13", subject: "Physics", chapter: "Thermodynamics", year: 2024, type: "MCQ",
    question: "A Carnot engine operates between 527 °C and 127 °C. Its efficiency is:",
    options: ["75%", "25%", "50%", "60%"], answer: 2,
    solution: "T₁ = 800 K, T₂ = 400 K. η = 1 − 400/800 = 0.5 = 50%." },
  { id: "P14", subject: "Physics", chapter: "Thermodynamics", year: 2026, type: "NUM",
    question: "2 moles of an ideal monatomic gas are heated at constant volume from 300 K to 400 K. Taking R = 8.3 J mol⁻¹ K⁻¹, the heat supplied (in J) is ____.",
    answer: 2490,
    solution: "Q = nC_vΔT = 2 × (3/2 × 8.3) × 100 = 2490 J." },
  { id: "P15", subject: "Physics", chapter: "Oscillations and Waves", year: 2025, type: "MCQ",
    question: "The time period of a simple pendulum is 2 s. If its length is increased by 44%, the new time period is:",
    options: ["2.88 s", "2.2 s", "2.4 s", "1.67 s"], answer: 2,
    solution: "T ∝ √L: T' = 2 × √1.44 = 2 × 1.2 = 2.4 s." },
  { id: "P16", subject: "Physics", chapter: "Oscillations and Waves", year: 2023, type: "MCQ",
    question: "A string 1 m long, fixed at both ends, vibrates in its fundamental mode at 100 Hz. The speed of transverse waves on the string is:",
    options: ["400 m/s", "50 m/s", "100 m/s", "200 m/s"], answer: 3,
    solution: "Fundamental: λ = 2L = 2 m. v = fλ = 100 × 2 = 200 m/s." },
  { id: "P17", subject: "Physics", chapter: "Electrostatics", year: 2024, type: "MCQ",
    question: "Two point charges +q and +4q are separated by a distance d. A third charge placed on the line joining them experiences zero net force. Its distance from +q is:",
    options: ["d/3", "d/2", "2d/3", "d/4"], answer: 0,
    solution: "kq/x² = k(4q)/(d − x)² ⇒ (d − x) = 2x ⇒ x = d/3." },
  { id: "P18", subject: "Physics", chapter: "Electrostatics", year: 2025, type: "NUM",
    question: "A parallel plate capacitor of capacitance 5 μF is charged to 100 V. The energy stored in it (in mJ) is ____.",
    answer: 25,
    solution: "U = ½CV² = ½ × 5 × 10⁻⁶ × 10⁴ = 0.025 J = 25 mJ." },
  { id: "P19", subject: "Physics", chapter: "Current Electricity", year: 2026, type: "MCQ",
    question: "A wire of resistance 16 Ω is bent into a circle. The effective resistance between two diametrically opposite points is:",
    options: ["16 Ω", "8 Ω", "4 Ω", "2 Ω"], answer: 2,
    solution: "Each semicircle is 8 Ω and they are in parallel: 8 × 8/16 = 4 Ω." },
  { id: "P20", subject: "Physics", chapter: "Current Electricity", year: 2023, type: "MCQ",
    question: "A cell of emf 12 V and internal resistance 1 Ω is connected across an external resistance of 5 Ω. The terminal potential difference of the cell is:",
    options: ["11 V", "2 V", "12 V", "10 V"], answer: 3,
    solution: "I = 12/(5 + 1) = 2 A. V = E − Ir = 12 − 2 = 10 V." },
  { id: "P21", subject: "Physics", chapter: "Magnetic Effects of Current", year: 2024, type: "MCQ",
    question: "A proton and an alpha particle enter a uniform magnetic field perpendicularly with the same speed. The ratio of the radii of their circular paths, r_{p} : r_{α}, is:",
    options: ["1 : 2", "2 : 1", "1 : 4", "1 : 1"], answer: 0,
    solution: "r = mv/qB. Proton: m/e. Alpha: 4m/2e = 2m/e. Ratio = 1 : 2." },
  { id: "P22", subject: "Physics", chapter: "Magnetic Effects of Current", year: 2025, type: "MCQ",
    question: "A circular coil of radius 10 cm has 100 turns and carries a current of 1 A. The magnetic field at its centre is (μ₀ = 4π × 10⁻⁷ T m A⁻¹):",
    options: ["3.14 × 10⁻⁴ T", "6.28 × 10⁻⁵ T", "6.28 × 10⁻⁴ T", "1.26 × 10⁻³ T"], answer: 2,
    solution: "B = μ₀NI/2R = 4π × 10⁻⁷ × 100 × 1 / 0.2 = 2π × 10⁻⁴ ≈ 6.28 × 10⁻⁴ T." },
  { id: "P23", subject: "Physics", chapter: "Electromagnetic Induction and AC", year: 2023, type: "MCQ",
    question: "In a series LCR circuit, L = 10 mH and C = 1 μF. The angular frequency at resonance is:",
    options: ["10³ rad/s", "10⁴ rad/s", "10⁵ rad/s", "10² rad/s"], answer: 1,
    solution: "ω₀ = 1/√(LC) = 1/√(10⁻² × 10⁻⁶) = 1/10⁻⁴ = 10⁴ rad/s." },
  { id: "P24", subject: "Physics", chapter: "Electromagnetic Induction and AC", year: 2026, type: "NUM",
    question: "The current in a coil of self-inductance 0.5 H decreases uniformly from 4 A to zero in 0.1 s. The magnitude of the induced emf (in V) is ____.",
    answer: 20,
    solution: "|e| = L ΔI/Δt = 0.5 × 4/0.1 = 20 V." },
  { id: "P25", subject: "Physics", chapter: "Ray Optics", year: 2024, type: "MCQ",
    question: "An object is placed 30 cm in front of a concave mirror of focal length 20 cm. The image is formed:",
    options: ["60 cm in front of the mirror", "60 cm behind the mirror", "12 cm in front of the mirror", "12 cm behind the mirror"], answer: 0,
    solution: "1/v = 1/f − 1/u = −1/20 + 1/30 = −1/60 ⇒ v = −60 cm, i.e. 60 cm in front (real image)." },
  { id: "P26", subject: "Physics", chapter: "Ray Optics", year: 2025, type: "MCQ",
    question: "The critical angle for light going from a medium to air is 30°. The refractive index of the medium is:",
    options: ["1.5", "√3", "√2", "2"], answer: 3,
    solution: "μ = 1/sin C = 1/sin 30° = 2." },
  { id: "P27", subject: "Physics", chapter: "Modern Physics", year: 2023, type: "MCQ",
    question: "The work function of a metal is 2.0 eV. Photons of energy 5.0 eV fall on it. The stopping potential is:",
    options: ["7 V", "5 V", "3 V", "2 V"], answer: 2,
    solution: "K_max = 5.0 − 2.0 = 3.0 eV, so V₀ = 3 V." },
  { id: "P28", subject: "Physics", chapter: "Modern Physics", year: 2026, type: "NUM",
    question: "A radioactive sample initially contains 1600 undecayed nuclei. Its half-life is 10 days. The number of undecayed nuclei left after 40 days is ____.",
    answer: 100,
    solution: "40 days = 4 half-lives. N = 1600/2⁴ = 100." },

  // ---------------- CHEMISTRY ----------------
  { id: "C01", subject: "Chemistry", chapter: "Some Basic Concepts of Chemistry", year: 2025, type: "MCQ",
    question: "The number of moles of oxygen atoms in 9.8 g of H₂SO₄ (molar mass 98 g mol⁻¹) is:",
    options: ["0.1", "0.4", "0.2", "0.04"], answer: 1,
    solution: "9.8/98 = 0.1 mol H₂SO₄, each with 4 O atoms: 0.4 mol O atoms." },
  { id: "C02", subject: "Chemistry", chapter: "Some Basic Concepts of Chemistry", year: 2023, type: "NUM",
    question: "The volume (in mL) of 0.5 M NaOH required to completely neutralise 50 mL of 0.25 M H₂SO₄ is ____.",
    answer: 50,
    solution: "mol H⁺ = 2 × 0.25 × 0.050 = 0.025. V(NaOH) = 0.025/0.5 = 0.050 L = 50 mL." },
  { id: "C03", subject: "Chemistry", chapter: "Atomic Structure", year: 2024, type: "MCQ",
    question: "The number of radial nodes in a 3p orbital is:",
    options: ["2", "0", "3", "1"], answer: 3,
    solution: "Radial nodes = n − l − 1 = 3 − 1 − 1 = 1." },
  { id: "C04", subject: "Chemistry", chapter: "Atomic Structure", year: 2026, type: "MCQ",
    question: "Which of the following sets of quantum numbers is NOT permissible?",
    options: ["n = 3, l = 2, mₗ = −2", "n = 2, l = 2, mₗ = 0", "n = 4, l = 0, mₗ = 0", "n = 3, l = 1, mₗ = +1"], answer: 1,
    solution: "l can take values 0 to n − 1. For n = 2, l = 2 is not allowed." },
  { id: "C05", subject: "Chemistry", chapter: "Chemical Bonding and Molecular Structure", year: 2025, type: "MCQ",
    question: "The hybridisation of the central atom and the shape of XeF₄ are respectively:",
    options: ["sp³d², square planar", "sp³d, see-saw", "sp³d², octahedral", "sp³, tetrahedral"], answer: 0,
    solution: "Xe has 4 bond pairs and 2 lone pairs (6 electron domains) ⇒ sp³d²; lone pairs trans ⇒ square planar." },
  { id: "C06", subject: "Chemistry", chapter: "Chemical Bonding and Molecular Structure", year: 2024, type: "MCQ",
    question: "Which of the following species is paramagnetic?",
    options: ["N₂", "CO", "O₂", "F₂"], answer: 2,
    solution: "By MO theory O₂ has two unpaired electrons in π* orbitals; the others have all electrons paired." },
  { id: "C07", subject: "Chemistry", chapter: "Chemical Thermodynamics", year: 2023, type: "MCQ",
    question: "For a reaction, ΔH = −40 kJ mol⁻¹ and ΔS = −100 J K⁻¹ mol⁻¹. Above what temperature does the reaction become non-spontaneous?",
    options: ["4000 K", "40 K", "400 K", "300 K"], answer: 2,
    solution: "ΔG = ΔH − TΔS becomes positive when T > ΔH/ΔS = 40000/100 = 400 K." },
  { id: "C08", subject: "Chemistry", chapter: "Chemical Thermodynamics", year: 2026, type: "NUM",
    question: "The standard enthalpies of formation of CO₂(g), H₂O(l) and CH₄(g) are −393, −286 and −75 kJ mol⁻¹ respectively. The magnitude of the standard enthalpy of combustion of methane (in kJ mol⁻¹) is ____.",
    answer: 890,
    solution: "CH₄ + 2O₂ → CO₂ + 2H₂O. ΔH = [−393 + 2(−286)] − (−75) = −890 kJ mol⁻¹." },
  { id: "C09", subject: "Chemistry", chapter: "Equilibrium", year: 2025, type: "MCQ",
    question: "For the reaction N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the relation between K_{p} and K_{c} is:",
    options: ["K_{p} = K_{c}(RT)²", "K_{p} = K_{c}(RT)⁻²", "K_{p} = K_{c}", "K_{p} = K_{c}(RT)⁻¹"], answer: 1,
    solution: "K_p = K_c(RT)^Δn with Δn = 2 − 4 = −2." },
  { id: "C10", subject: "Chemistry", chapter: "Equilibrium", year: 2024, type: "MCQ",
    question: "The pH of a 0.001 M NaOH solution at 25 °C is:",
    options: ["12", "10", "3", "11"], answer: 3,
    solution: "[OH⁻] = 10⁻³ M, pOH = 3, pH = 14 − 3 = 11." },
  { id: "C11", subject: "Chemistry", chapter: "Redox Reactions and Electrochemistry", year: 2023, type: "MCQ",
    question: "The oxidation state of chromium in K₂Cr₂O₇ is:",
    options: ["+6", "+3", "+7", "+4"], answer: 0,
    solution: "2(+1) + 2x + 7(−2) = 0 ⇒ x = +6." },
  { id: "C12", subject: "Chemistry", chapter: "Redox Reactions and Electrochemistry", year: 2025, type: "NUM",
    question: "The standard emf of the cell Zn | Zn²⁺ || Cu²⁺ | Cu is 1.1 V. If ΔG° for the cell reaction is −x kJ mol⁻¹, the value of x (nearest integer) is ____. (F = 96500 C mol⁻¹)",
    answer: 212,
    solution: "ΔG° = −nFE° = −2 × 96500 × 1.1 = −212300 J ≈ −212 kJ mol⁻¹." },
  { id: "C13", subject: "Chemistry", chapter: "Chemical Kinetics", year: 2024, type: "MCQ",
    question: "The half-life of a first-order reaction is 30 minutes. The time required for 75% completion of the reaction is:",
    options: ["90 min", "45 min", "120 min", "60 min"], answer: 3,
    solution: "75% completion = 2 half-lives = 60 min." },
  { id: "C14", subject: "Chemistry", chapter: "Chemical Kinetics", year: 2026, type: "MCQ",
    question: "For the reaction 2A + B → products, rate = k[A][B]². If the concentrations of both A and B are doubled, the rate increases by a factor of:",
    options: ["4", "6", "8", "16"], answer: 2,
    solution: "New rate = k(2[A])(2[B])² = 8 × old rate." },
  { id: "C15", subject: "Chemistry", chapter: "Solutions", year: 2023, type: "MCQ",
    question: "Which of the following aqueous solutions has the highest boiling point?",
    options: ["0.1 m KCl", "0.1 m glucose", "0.1 m Na₂SO₄", "0.1 m urea"], answer: 2,
    solution: "ΔT_b ∝ i·m. Na₂SO₄ gives i = 3, the largest of the four." },
  { id: "C16", subject: "Chemistry", chapter: "Solutions", year: 2025, type: "NUM",
    question: "18 g of glucose (molar mass 180 g mol⁻¹) is dissolved in 1 kg of water. Taking K_{b} = 0.50 K kg mol⁻¹, the elevation in boiling point is x × 10⁻² K. The value of x is ____.",
    answer: 5,
    solution: "m = 0.1 mol kg⁻¹. ΔT_b = 0.50 × 0.1 = 0.05 K = 5 × 10⁻² K." },
  { id: "C17", subject: "Chemistry", chapter: "p-Block Elements", year: 2024, type: "MCQ",
    question: "Which of the following is the strongest acid?",
    options: ["HClO", "HClO₂", "HClO₃", "HClO₄"], answer: 3,
    solution: "Acid strength of chlorine oxoacids rises with the oxidation state of Cl; the conjugate base ClO₄⁻ is the most resonance-stabilised." },
  { id: "C18", subject: "Chemistry", chapter: "p-Block Elements", year: 2026, type: "MCQ",
    question: "The number of P–O–P bridge bonds in P₄O₁₀ is:",
    options: ["4", "5", "6", "10"], answer: 2,
    solution: "P₄O₁₀ has a P₄ tetrahedral framework with 6 bridging O atoms (one per edge) and 4 terminal P=O." },
  { id: "C19", subject: "Chemistry", chapter: "d- and f-Block Elements", year: 2025, type: "MCQ",
    question: "The spin-only magnetic moment of Fe³⁺ (Z = 26) is:",
    options: ["3.87 BM", "1.73 BM", "4.90 BM", "5.92 BM"], answer: 3,
    solution: "Fe³⁺ is 3d⁵ with 5 unpaired electrons: μ = √(5 × 7) = √35 ≈ 5.92 BM." },
  { id: "C20", subject: "Chemistry", chapter: "d- and f-Block Elements", year: 2023, type: "MCQ",
    question: "Lanthanoid contraction is caused by:",
    options: ["imperfect shielding of one 4f electron by another", "an increase in atomic mass", "strong shielding by 5d electrons", "a decrease in nuclear charge"], answer: 0,
    solution: "4f orbitals are diffuse and shield poorly, so the effective nuclear charge rises across the series and the radii shrink." },
  { id: "C21", subject: "Chemistry", chapter: "Coordination Compounds", year: 2024, type: "MCQ",
    question: "The IUPAC name of [Co(NH₃)₆]Cl₃ is:",
    options: ["hexaamminecobalt(II) chloride", "hexaamminecobalt(III) chloride", "cobalt hexaammine chloride", "hexaamminecobaltate(III) chloride"], answer: 1,
    solution: "Six neutral NH₃ ligands and 3 Cl⁻ counter-ions ⇒ Co is +3. Cationic complex, so the metal name is unchanged: hexaamminecobalt(III) chloride." },
  { id: "C22", subject: "Chemistry", chapter: "Coordination Compounds", year: 2026, type: "NUM",
    question: "The number of geometrical isomers possible for the square planar complex [Pt(NH₃)(Br)(Cl)(py)] is ____.",
    answer: 3,
    solution: "A square planar [Mabcd] complex has 3 geometrical isomers (fix a; choose which of b, c, d is trans to it)." },
  { id: "C23", subject: "Chemistry", chapter: "Organic Chemistry: Basic Principles", year: 2025, type: "MCQ",
    question: "Which of the following carbocations is the most stable?",
    options: ["CH₃⁺", "CH₃CH₂⁺", "(CH₃)₂CH⁺", "(CH₃)₃C⁺"], answer: 3,
    solution: "Stability rises with alkyl substitution (hyperconjugation and +I effect): 3° > 2° > 1° > methyl." },
  { id: "C24", subject: "Chemistry", chapter: "Hydrocarbons", year: 2023, type: "MCQ",
    question: "Addition of HBr to propene in the presence of benzoyl peroxide gives mainly:",
    options: ["2-bromopropane", "1-bromopropane", "1,2-dibromopropane", "propane"], answer: 1,
    solution: "Peroxide effect (Kharasch): free-radical, anti-Markovnikov addition gives 1-bromopropane." },
  { id: "C25", subject: "Chemistry", chapter: "Alcohols, Aldehydes and Ketones", year: 2024, type: "MCQ",
    question: "Which of the following compounds gives a positive iodoform test?",
    options: ["Propan-1-ol", "Methanol", "Benzyl alcohol", "Ethanol"], answer: 3,
    solution: "Ethanol is oxidised to ethanal (CH₃CHO), which has the CH₃CO– group needed for the iodoform reaction." },
  { id: "C26", subject: "Chemistry", chapter: "Alcohols, Aldehydes and Ketones", year: 2025, type: "MCQ",
    question: "Which reagent can distinguish ethanal from propanone?",
    options: ["2,4-DNP", "NaHSO₃", "Tollens' reagent", "I₂ and NaOH"], answer: 2,
    solution: "Only the aldehyde reduces Tollens' reagent (silver mirror). Both give positive 2,4-DNP, bisulphite and iodoform tests." },
  { id: "C27", subject: "Chemistry", chapter: "Biomolecules", year: 2026, type: "MCQ",
    question: "The glycosidic linkage in sucrose is between:",
    options: ["C1 of α-D-glucose and C2 of β-D-fructose", "C1 of α-D-glucose and C4 of α-D-glucose", "C1 of β-D-glucose and C4 of β-D-glucose", "C1 of β-D-galactose and C4 of β-D-glucose"], answer: 0,
    solution: "Sucrose is α-D-glucopyranosyl-(1→2)-β-D-fructofuranoside, a non-reducing sugar." },
  { id: "C28", subject: "Chemistry", chapter: "Biomolecules", year: 2024, type: "NUM",
    question: "The number of essential amino acids among the following is ____:\nValine, Glycine, Leucine, Alanine, Lysine, Serine, Threonine, Tyrosine",
    answer: 4,
    solution: "Essential: valine, leucine, lysine, threonine. Glycine, alanine, serine and tyrosine can be synthesised by the body." },

  // ---------------- MATHEMATICS ----------------
  { id: "M01", subject: "Mathematics", chapter: "Sets, Relations and Functions", year: 2025, type: "MCQ",
    question: "The number of reflexive relations on a set with 3 elements is:",
    options: ["512", "64", "8", "256"], answer: 1,
    solution: "The 3 diagonal pairs are fixed; each of the other 3² − 3 = 6 pairs is free: 2⁶ = 64." },
  { id: "M02", subject: "Mathematics", chapter: "Sets, Relations and Functions", year: 2023, type: "MCQ",
    question: "The domain of f(x) = 1/√(x² − 4) is:",
    options: ["(−∞, −2) ∪ (2, ∞)", "[−2, 2]", "(−2, 2)", "(−∞, −2] ∪ [2, ∞)"], answer: 0,
    solution: "Need x² − 4 > 0 (strictly, as it is under a root in the denominator): |x| > 2." },
  { id: "M03", subject: "Mathematics", chapter: "Complex Numbers", year: 2024, type: "MCQ",
    question: "If z = (1 + i)/(1 − i), then z¹⁰⁰ equals:",
    options: ["−1", "i", "1", "−i"], answer: 2,
    solution: "z = (1 + i)²/2 = 2i/2 = i. i¹⁰⁰ = (i⁴)²⁵ = 1." },
  { id: "M04", subject: "Mathematics", chapter: "Complex Numbers", year: 2026, type: "NUM",
    question: "The modulus of (3 + 4i)(5 − 12i) is ____.",
    answer: 65,
    solution: "|z₁z₂| = |z₁||z₂| = 5 × 13 = 65." },
  { id: "M05", subject: "Mathematics", chapter: "Quadratic Equations", year: 2025, type: "MCQ",
    question: "If α and β are the roots of x² − 5x + 6 = 0, then α² + β² equals:",
    options: ["25", "11", "13", "12"], answer: 2,
    solution: "α + β = 5, αβ = 6. α² + β² = 25 − 12 = 13." },
  { id: "M06", subject: "Mathematics", chapter: "Quadratic Equations", year: 2023, type: "NUM",
    question: "The number of real values of x satisfying x² − 5|x| + 6 = 0 is ____.",
    answer: 4,
    solution: "|x|² − 5|x| + 6 = 0 ⇒ |x| = 2 or 3 ⇒ x = ±2, ±3." },
  { id: "M07", subject: "Mathematics", chapter: "Matrices and Determinants", year: 2024, type: "MCQ",
    question: "If A is a 3 × 3 matrix with |A| = 4, then |adj A| equals:",
    options: ["64", "8", "4", "16"], answer: 3,
    solution: "|adj A| = |A|ⁿ⁻¹ = 4² = 16." },
  { id: "M08", subject: "Mathematics", chapter: "Matrices and Determinants", year: 2026, type: "MCQ",
    question: "If A = [2 3 ; 1 2] (rows separated by ;), then A⁻¹ is:",
    options: ["[2 −3 ; −1 2]", "[−2 3 ; 1 −2]", "[2 −1 ; −3 2]", "[½ ⅓ ; 1 ½]"], answer: 0,
    solution: "|A| = 4 − 3 = 1, so A⁻¹ = adj A = [2 −3 ; −1 2]." },
  { id: "M09", subject: "Mathematics", chapter: "Permutations and Combinations", year: 2025, type: "MCQ",
    question: "The number of distinct arrangements of the letters of the word LEVEL is:",
    options: ["120", "60", "30", "20"], answer: 2,
    solution: "5!/(2! 2!) = 120/4 = 30 (L and E each repeat twice)." },
  { id: "M10", subject: "Mathematics", chapter: "Permutations and Combinations", year: 2024, type: "NUM",
    question: "The number of ways of forming a committee of 3 men and 2 women from 6 men and 5 women is ____.",
    answer: 200,
    solution: "⁶C₃ × ⁵C₂ = 20 × 10 = 200." },
  { id: "M11", subject: "Mathematics", chapter: "Binomial Theorem", year: 2023, type: "MCQ",
    question: "The coefficient of x⁴ in the expansion of (1 + x)¹⁰ is:",
    options: ["120", "210", "252", "45"], answer: 1,
    solution: "¹⁰C₄ = 210." },
  { id: "M12", subject: "Mathematics", chapter: "Binomial Theorem", year: 2026, type: "MCQ",
    question: "The term independent of x in the expansion of (x + 1/x)⁸ is:",
    options: ["56", "28", "8", "70"], answer: 3,
    solution: "T_{r+1} = ⁸C_r x^{8−2r}; 8 − 2r = 0 ⇒ r = 4. ⁸C₄ = 70." },
  { id: "M13", subject: "Mathematics", chapter: "Sequences and Series", year: 2025, type: "MCQ",
    question: "The sum of the infinite geometric series 1 + 1/3 + 1/9 + … is:",
    options: ["3/2", "4/3", "2", "3"], answer: 0,
    solution: "S = a/(1 − r) = 1/(1 − 1/3) = 3/2." },
  { id: "M14", subject: "Mathematics", chapter: "Sequences and Series", year: 2024, type: "NUM",
    question: "The 3rd and 7th terms of an AP are 12 and 28 respectively. The 10th term is ____.",
    answer: 40,
    solution: "4d = 16 ⇒ d = 4, a = 12 − 8 = 4. a₁₀ = 4 + 9 × 4 = 40." },
  { id: "M15", subject: "Mathematics", chapter: "Limits, Continuity and Differentiability", year: 2023, type: "MCQ",
    question: "lim_{x→0} (sin 3x)/x equals:",
    options: ["0", "1", "3", "1/3"], answer: 2,
    solution: "(sin 3x)/x = 3 · (sin 3x)/(3x) → 3 × 1 = 3." },
  { id: "M16", subject: "Mathematics", chapter: "Limits, Continuity and Differentiability", year: 2025, type: "MCQ",
    question: "lim_{x→0} (eˣ − 1 − x)/x² equals:",
    options: ["1", "1/2", "0", "2"], answer: 1,
    solution: "eˣ = 1 + x + x²/2 + …, so the expression → 1/2." },
  { id: "M17", subject: "Mathematics", chapter: "Applications of Derivatives", year: 2024, type: "MCQ",
    question: "The local maximum value of f(x) = x³ − 3x + 2 is:",
    options: ["2", "6", "0", "4"], answer: 3,
    solution: "f'(x) = 3x² − 3 = 0 ⇒ x = ±1; f''(−1) = −6 < 0, so the local max is f(−1) = −1 + 3 + 2 = 4." },
  { id: "M18", subject: "Mathematics", chapter: "Applications of Derivatives", year: 2026, type: "MCQ",
    question: "The slope of the tangent to the curve y = x³ − 2x + 1 at x = 2 is:",
    options: ["10", "12", "8", "5"], answer: 0,
    solution: "dy/dx = 3x² − 2 = 12 − 2 = 10 at x = 2." },
  { id: "M19", subject: "Mathematics", chapter: "Integral Calculus", year: 2025, type: "MCQ",
    question: "The value of ∫₀^{π/2} sin²x dx is:",
    options: ["π/2", "π/4", "1", "π"], answer: 1,
    solution: "∫₀^{π/2} sin²x dx = ∫₀^{π/2} cos²x dx and their sum is π/2, so each is π/4." },
  { id: "M20", subject: "Mathematics", chapter: "Integral Calculus", year: 2023, type: "NUM",
    question: "The value of ∫₀² (3x² + 2x) dx is ____.",
    answer: 12,
    solution: "[x³ + x²]₀² = 8 + 4 = 12." },
  { id: "M21", subject: "Mathematics", chapter: "Differential Equations", year: 2024, type: "MCQ",
    question: "The order and degree of the differential equation (d²y/dx²)³ + (dy/dx)⁴ + y = 0 are respectively:",
    options: ["2, 3", "3, 2", "2, 4", "4, 2"], answer: 0,
    solution: "Highest derivative is d²y/dx² (order 2), raised to the power 3 (degree 3)." },
  { id: "M22", subject: "Mathematics", chapter: "Differential Equations", year: 2026, type: "MCQ",
    question: "The general solution of dy/dx = y/x (x, y > 0) is:",
    options: ["xy = c", "y = cx", "y = x + c", "y = ceˣ"], answer: 1,
    solution: "dy/y = dx/x ⇒ ln y = ln x + ln c ⇒ y = cx." },
  { id: "M23", subject: "Mathematics", chapter: "Coordinate Geometry", year: 2025, type: "MCQ",
    question: "The distance between the parallel lines 3x + 4y − 7 = 0 and 6x + 8y + 6 = 0 is:",
    options: ["1", "4/5", "2", "10/7"], answer: 2,
    solution: "Second line: 3x + 4y + 3 = 0. d = |−7 − 3|/√(9 + 16) = 10/5 = 2." },
  { id: "M24", subject: "Mathematics", chapter: "Coordinate Geometry", year: 2024, type: "MCQ",
    question: "The eccentricity of the ellipse x²/25 + y²/16 = 1 is:",
    options: ["4/5", "3/5", "3/4", "5/3"], answer: 1,
    solution: "e = √(1 − b²/a²) = √(1 − 16/25) = 3/5." },
  { id: "M25", subject: "Mathematics", chapter: "Coordinate Geometry", year: 2023, type: "NUM",
    question: "The length of the latus rectum of the parabola y² = 12x is ____.",
    answer: 12,
    solution: "y² = 4ax with a = 3; latus rectum = 4a = 12." },
  { id: "M26", subject: "Mathematics", chapter: "Vectors and 3D Geometry", year: 2025, type: "MCQ",
    question: "If a⃗ = î + 2ĵ + 3k̂ and b⃗ = 2î − ĵ + k̂, then a⃗ · b⃗ equals:",
    options: ["5", "1", "7", "3"], answer: 3,
    solution: "1(2) + 2(−1) + 3(1) = 3." },
  { id: "M27", subject: "Mathematics", chapter: "Vectors and 3D Geometry", year: 2026, type: "NUM",
    question: "The perpendicular distance of the point (1, 2, 3) from the plane 2x − y + 2z + 3 = 0 is ____.",
    answer: 3,
    solution: "|2 − 2 + 6 + 3|/√(4 + 1 + 4) = 9/3 = 3." },
  { id: "M28", subject: "Mathematics", chapter: "Probability", year: 2024, type: "MCQ",
    question: "Two fair dice are thrown. The probability that the sum of the numbers shown is 7 is:",
    options: ["1/6", "5/36", "1/12", "7/36"], answer: 0,
    solution: "Favourable outcomes: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) = 6 of 36 = 1/6." }
];
