"""
Bundle every extracted paper under pyq/<year>/<shift>/questions.json into
pyq_bank.js (window.JEE_PYQ_BANK), which index.html loads as the built-in bank.

Questions NTA dropped, or whose final key has no single answer, are left out
(they stay listed in each paper's review.csv).

Usage:  python tools/build_pyq_bank.py
"""
import glob, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEEP = ['id', 'subject', 'chapter', 'year', 'type', 'source', 'question', 'image',
        'options', 'option_images', 'answer', 'accept', 'solution']

bank, skipped, papers = [], [], []
for path in sorted(glob.glob(os.path.join(ROOT, 'pyq', '*', '*', 'questions.json'))):
    folder = os.path.relpath(os.path.dirname(path), ROOT).replace(os.sep, '/')
    paper = json.load(open(path, encoding='utf-8'))
    n = 0
    for q in paper['questions']:
        if q.get('exclude'):
            skipped.append(f"{q['source']}: {q['exclude']}"); continue
        if q.get('answer') is None:
            skipped.append(f"{q['source']}: no answer"); continue
        r = {k: q[k] for k in KEEP if k in q}
        if 'image' in r: r['image'] = f"{folder}/{r['image']}"
        if 'option_images' in r: r['option_images'] = [f'{folder}/{p}' if p else '' for p in r['option_images']]
        bank.append(r); n += 1
    papers.append(f"{paper['source']}: {n}")

with open(os.path.join(ROOT, 'pyq_bank.js'), 'w', encoding='utf-8') as f:
    f.write('/* Generated by tools/build_pyq_bank.py. Do not edit by hand.\n'
            ' * Official questions from public NTA question papers (images as printed by NTA),\n'
            " * answers from NTA's FINAL answer keys. Sources: sources/<year>/SOURCES.md */\n")
    f.write('window.JEE_PYQ_BANK = ')
    json.dump(bank, f, ensure_ascii=False, separators=(',', ':'))
    f.write(';\n')
print('\n'.join(papers))
print(f'{len(bank)} questions in pyq_bank.js; left out {len(skipped)}:')
print('\n'.join('  ' + s for s in skipped))
