"""
Bundle every extracted paper under pyq/<year>/<shift>/questions.json into
pyq_bank.js (window.JEE_PYQ_BANK), which index.html loads as the built-in bank.

Questions NTA dropped, or whose final key has no single answer, are left out
(they stay listed in each paper's review.csv).

Chapter tags come from pyq/<year>/<shift>/tags.csv (written by Claude after reading each
question image; see tools/chapters.py). They are kept apart from questions.json so that
re-running the extractor never wipes them. Every code is checked against the official list
and against the question's subject from NTA's paper.

Usage:  python tools/build_pyq_bank.py
"""
import csv, glob, json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from chapters import CODES

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEEP = ['id', 'subject', 'chapter', 'subtopic', 'secondary_chapter', 'tag_confidence', 'year', 'type',
        'source', 'question', 'image', 'options', 'option_images', 'answer', 'accept', 'solution']


def load_tags(folder, questions):
    """{question id: tag fields} from tags.csv (q = question number in the paper)."""
    path = os.path.join(folder, 'tags.csv')
    if not os.path.exists(path):
        return {}
    tags, errors = {}, []
    for row in csv.DictReader(open(path, encoding='utf-8')):
        n = int(row['q']); q = questions[n - 1]
        code, sec = row['chapter'].strip(), (row.get('secondary') or '').strip()
        if code not in CODES:
            errors.append(f'Q{n}: unknown chapter code {code}'); continue
        subj, chap = CODES[code]
        if subj != q['subject']:
            errors.append(f"Q{n}: code {code} is {subj} but NTA lists the question under {q['subject']}"); continue
        t = {'chapter': chap, 'subtopic': row['subtopic'].strip(),
             'tag_confidence': row['confidence'].strip()}
        if sec:
            if sec not in CODES:
                errors.append(f'Q{n}: unknown secondary code {sec}'); continue
            t['secondary_chapter'] = CODES[sec][1]
        if t['tag_confidence'] not in ('high', 'low'):
            errors.append(f'Q{n}: confidence must be high or low')
        tags[q['id']] = t
    if errors:
        raise SystemExit(f'{path}:' + ''.join('\n  ' + e for e in errors))
    return tags

bank, skipped, papers = [], [], []
for path in sorted(glob.glob(os.path.join(ROOT, 'pyq', '*', '*', 'questions.json'))):
    folder = os.path.relpath(os.path.dirname(path), ROOT).replace(os.sep, '/')
    paper = json.load(open(path, encoding='utf-8'))
    tags = load_tags(os.path.dirname(path), paper['questions'])
    untagged = 0
    n = 0
    for q in paper['questions']:
        if q.get('exclude'):
            skipped.append(f"{q['source']}: {q['exclude']}"); continue
        if q.get('answer') is None:
            skipped.append(f"{q['source']}: no answer"); continue
        q = dict(q, **tags.get(q['id'], {}))
        if q['id'] not in tags: untagged += 1
        r = {k: q[k] for k in KEEP if k in q}
        if 'image' in r: r['image'] = f"{folder}/{r['image']}"
        if 'option_images' in r: r['option_images'] = [f'{folder}/{p}' if p else '' for p in r['option_images']]
        bank.append(r); n += 1
    papers.append(f"{paper['source']}: {n}" + (f' ({untagged} not tagged yet)' if untagged else ''))

with open(os.path.join(ROOT, 'pyq_bank.js'), 'w', encoding='utf-8') as f:
    f.write('/* Generated by tools/build_pyq_bank.py. Do not edit by hand.\n'
            ' * Official questions from public NTA question papers (images as printed by NTA),\n'
            " * answers from NTA's FINAL answer keys. Sources: sources/<year>/SOURCES.md */\n")
    f.write('window.JEE_PYQ_BANK = ')
    json.dump(bank, f, ensure_ascii=False, separators=(',', ':'))
    f.write(';\n')
print('\n'.join(papers))
print(f'{len(bank)} questions in pyq_bank.js; left out {len(skipped)}:')
print('\n'.join('  ' + s for s in skipped))
